//Each new term in the Fibonacci sequence is generated by adding the previous two terms. By starting with 1 and 2, the first 10 terms will be:

//1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...

//By considering the terms in the Fibonacci sequence whose values do not exceed four million, find the sum of the even-valued terms.


var FiboSum = function(upper){
	var seq = [1,1,2];
	var sum = 0;
	while(seq[2] < limit){
		if (seq[2] % 2 === 0){
			sum += seq[2];
		}
		seq[0] = seq[1];
		seq[1] = seq[2];
		seq[2] = seq[0] + seq[1];
	}
	return sum;
};

console.log(FiboSum(10));